services:
  ms-deploy-network:
    networks:
      - vibolbanknet

  ms-base:
    extends: ms-deploy-network
    mem_limit: 700m
    
  ms-base-configserver:
    extends: ms-base
    depends_on: 
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  ms-base-eurekaserver:
    extends: ms-base-configserver
    depends_on: 
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9001/eureka/